apiVersion: v1
kind: Service
metadata:
  name: ipsec-policy-manager-controller-manager-metrics-service
  namespace: ipsec-policy-operator
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipsec-policy-manager-operator
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
