apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipsec-policy-manager-controller-manager
  namespace: ipsec-policy-operator
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipsec-policy-manager-operator
