apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: ipsec-policy-manager-operator
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: ipsec-policy-manager-operator
  name: ipsec-policy-manager-serving-cert
  namespace: ipsec-policy-operator
spec:
  dnsNames:
  - ipsec-policy-manager-webhook-service.ipsec-policy-operator.svc
  - ipsec-policy-manager-webhook-service.ipsec-policy-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ipsec-policy-manager-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipsec-policy-manager-operator
  name: ipsec-policy-manager-selfsigned-issuer
  namespace: ipsec-policy-operator
spec:
  selfSigned: {}
