---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-ipsec-policy-operator-tox-py39
        - k8sapp-ipsec-policy-operator-tox-flake8
        - k8sapp-ipsec-policy-operator-tox-pylint
        - k8sapp-ipsec-policy-operator-tox-metadata
        - k8sapp-ipsec-policy-operator-tox-bandit
        - stx-ipsec-policy-manager-operator-tox-go-lint
        - stx-ipsec-policy-agent-operator-tox-go-lint
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-ipsec-policy-operator-tox-py39
        - k8sapp-ipsec-policy-operator-tox-flake8
        - k8sapp-ipsec-policy-operator-tox-pylint
        - k8sapp-ipsec-policy-operator-tox-metadata
        - k8sapp-ipsec-policy-operator-tox-bandit
        - stx-ipsec-policy-manager-operator-tox-go-lint
        - stx-ipsec-policy-agent-operator-tox-go-lint
    post:
      jobs:
        - stx-app-ipsec-policy-operator-upload-git-mirror

- job:
    name: k8sapp-ipsec-policy-operator-tox-py39
    parent: openstack-tox-py39
    description: |
      Run py39 test for k8sapp-ipsec-policy-operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ipsec-policy-operator/*
    vars:
      tox_extra_args: -c python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ipsec-policy-operator-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp-ipsec-policy-operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ipsec-policy-operator/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ipsec-policy-operator-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp-ipsec-policy-operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ipsec-policy-operator-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp-ipsec-policy-operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ipsec-policy-operator/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ipsec-policy-operator-tox-bandit
    parent: tox
    description: |
      Run bandit test for k8sapp-ipsec-policy-operator
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ipsec-policy-operator/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-app-ipsec-policy-operator-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-ipsec-policy-operator to
      github.com/starlingx/app-ipsec-policy-operator
    vars:
      git_mirror_repository: starlingx/app-ipsec-policy-operator
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-ipsec-policy-operator-github-secret3
        pass-to-parent: true

- job:
    name: stx-ipsec-policy-manager-operator-tox-go-lint
    parent: golangci-lint
    description: |
            Run go linting for ipsec-policy-manager-operator
    vars:
      go_version: 1.24.3
      golangci_lint_version: 2.1.6
      zuul_work_dir: "{{ zuul.project.src_dir }}/ipsec-policy-manager-operator"

- job:
    name: stx-ipsec-policy-agent-operator-tox-go-lint
    parent: golangci-lint
    description: |
            Run go linting for ipsec-policy-agent-operator
    vars:
      go_version: 1.24.3
      golangci_lint_version: 2.1.6
      zuul_work_dir: "{{ zuul.project.src_dir }}/ipsec-policy-agent-operator"

- secret:
    name: stx-app-ipsec-policy-operator-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - cthlGVSyokiqU9ii3JnAfyDhpbV9BOR+rmidjUcFb3Ic2dp4Wf3NiLNzwTRH8CpVlEKHr
          TUR6lPkAMUhlxE66rK2hz0F6OOdEjV3zwCD4fdTeQoC64Xu1VFKrVEQwdxiIlWhFEK/ct
          ja2fvZX1lGRetNB/8XqJGvmidKSfPwxJvXR9mzcw94sS3d5Wdeshg9yGq5zLiHIy6aJR1
          6jS8swzVDofVjKhmU+/YCcg+fz1KFRUkZVq6V+dFoamIfV3b9c5PUDJsCpx8nCBS+YTLi
          SpSUSIxoduqFyvVHh+3ifzUAT+H+hrcN1gwRnt5xhfSaaTrMXXDMk4LmJsycOZ3PHcxYD
          nwkSNq/TcV0BPC9jd1i0qEVw502dhww/MANxCV6GDM1GCmSJNVdXtHoZ0vYQz/BgwhJ66
          1B+CodegQZGcACfrjv2eKiCWc1n+qR8LKcNH2QB5vKYNNJAL/zzneA0jLgJwbBHsnEZGz
          IkibSuTfrZ7Wjj+0AsNi3ErRdZQNfMGpGNgdGYfGzhhTAHxx9boY+sBK54P6ZVdPD4as6
          BNcVHVQWa4qoFNqqAtXhb2FqiMvnQSg/LZaVANZ2VvRBniuKN0iYKKtKXLGMlmVWVGAnV
          H7qJQ8kRDXCSyzBcDZcQ+LJ+LEVy6uF1MQ2RGfESs021l4ZfKcmNYEzGf0jR0M=
        - bITOb+y0reRXRrtTasR7g5A0eIThq0vuwwbP40Wakqgvw0YfQFvwpxi8Iem6RNURXDLEe
          uP3c/vvl/PlrsUG+NUMR7xJHr+/Ghk/GNUQPqheD028tTZOUz0xcrdC6rRcIjanq/whYJ
          c1uRyNmaqgHowUK9V5548rU4FS3CamdcDjAJfaKO5P2zBS1w6+ktRKzsyJjJ1Z839nqyF
          po67ihfSvpXjcFx/KEh+89AwBMM0ObMHC7ECfPyPu4DEt1c1856xKxAqCy4RNu282XCI6
          nZ3ymbKMEujeEKcEOEXLYIqdy81FrkLDDw2Bk7/uhADQZifWvLmS0i0R0f/sEcqqwoAsc
          wAx/4obZbf1rP6kolfKD57bRsO8IQR58ibvecg0DZYuc26o9H6HvtWZUtY7zevPVUMP0K
          +54Wi/33Dwy1O1qbmbB7Ps3yfHIolbljoYDsOI7ZkpRo9IPyCShT5k9VREl1uiHyPPVJd
          /ifPAtQitFIR0WGYB4rJHleFcAzz1qJ/RoZvnSM8v8yB+SqsxvR6Xn4462HXdRehrygdi
          anwZ58WVmglJrLJExW5odr1yVhYYiMXuuC7kxxSuhAbPNyNq80W4ZYhU8ysiH1bRo4y+G
          1+sKGK7MjdmA/4uoT9PGB/K+62BWVt751F9/CkDldAqO9N3wCpwcyQ0S9CuCDI=
        - pe6uY/qN22Mxl5zTSrXgoGcxFjxOazz2h95rmduP14VsnqwQViiVpuCSHYvPVIi9G7OC+
          pmw1Kp93VIIbnsQNfpYrpdDFUFUjJqzsOAr0MCyjd73b5+Ze0yw0Zx/StyCKwNnuQWXmg
          EVHs+8hlQR7WWhYt3E3blf3NYI0ED0wHR5OYhorR0pJ9jUqY5kOWYnmVmxEWD+llvdeN0
          ra3CdXBulXm0108zjgPpvbkaPr0HengcTQXLHiPYkbci0L5PB/UjRjZbibm7TDxUP282J
          UzuOVd7zBlXpNnp7fpgdK5d/c/PfiRWIB/mcA/RjC8p9pAtfRpivkhOyznYBy9nBKRoGw
          Gi1FTMayfKRH3rJhdviSihWH9oLAy1g8pPApZer9gIVd1QXoowoKaDUbbUlt+QKHGvz0e
          pWNyihA3OWd9GEB3qcIKLmqTy3A08cFkgwIN1/d3qZ0fuSzw9MNpj2/IRiOHIKEqiyQJl
          XeEThD6+hCqd7cdobOZQ2F6nJZdIx5tUVh2C2lb+gYqYt2Ljd520fPJT0Mg2TZf7KI5V/
          kgJ3uIjxKiKn9KQNaaFzYJlq9puGkVm5S47CKt+aFE5Z7ly3HTYyPWXN6hx0iAWm3D8kX
          2ay/ObmJIZIHd9FHKrMQan5OE2GWMVMwoI89wfIr/Xig56+zU8unlkEzEHx1kc=
        - mSrlzAjr+g+bW7vOMIUW/L8T58lmzmbWbMmyfbi/6IBGtp47A6htS+Obg9ubtiR79VM6o
          nLOjb7ZmBHQK1CPXkCVNXmUiLeWzqntcTpTtfnF9H+a6xvosrXqF6Xf8duZ+yb5k6tINc
          zaF8NE643gAk7dQryJRyxtCAzFCE4A3d0osS5FT/zO9Dpu7m0nwYtraRgX+smWDUWEn3m
          0xsGRSZnyulBOCjBl63aQEVg1X0VpmnZ2xdhho1RKETJvl2AXEZXnbN55upKTBdxAZQM7
          fl53T26j/VBDE4Vi8czdfzz3KgHjjEL75vIXfdjK5rMC0FEe3v+J847kcQRc7q9WV+Z+6
          mHc2fKq4PB3qD0zc2ESEtrrspNMdF2wrstjExXn91O7hjvScBTQru+Drfp4ZVCLCVyKqJ
          QKAFgB1s56IavLmNnrLQfWot3b/b4ai00KcUaEXmhUhG/7PVgccCstFsAG10X0Gmz1qQV
          IPGWdXitogqBYdn7Yda5o2FzWgHslc6tJk5s3Z7Tr/MOMVDbriAysC7F8QKGEDRy4L9nF
          qbxHBsAfDsPFX8WoZD7b3gkQI//Fg31E73Z9+5uGkidLDLJq7sPBnnJjIDSqsV8VF1Gmb
          qhPHAQJDJF61+X8CU6F2BMF2Q7j4XR85t8ZTcg3y2S72lhKeWNlZRz0BmXr4rI=
        - bcVVcxqDHAPAEZTmS/Z7YhqxPQ/xM4wJeTDaHUUx9R287ex1rp6+nxth97bWLVlp0ankv
          TYmeghIuQS7URcSP7VonAhWaQJAkpHSj/5hZZIOiS8/zhW832TfipyygmssScu/wHP4Zm
          mZ6Y4AHWidZOOpIcPP5lbvkGaNjMxd0/t7keS5CrfKiFJ8lvX0wzA4otJoH4LtFIrjYEp
          dm/GxlJbEJQxVA/XT4ppVyrS7l+oG2wMLRayp+4OrWqd5/HPh/vlx2g2FpGj3yeZxOfyc
          3oeK76nyNaMuIh7mlRCnV500RhOcWMVUJOlQl6L+GkXBEPKZNXDSJ136w+J0/dx50/4ed
          fTtge0w4Xabo8EZBJjyWx6EjOW8cmjEgoF8jezNePBbo5cY3onzbnJVqtyqpbuTX0d7Vo
          OSbgZVbix0oG0pIdTQmBrLQbNRPB6KWoXJQr3wPGl5/hpN3S8fHdqZTgWEM99RfoGYhzB
          XzaNfVQTgbWMBCoKll3F4E7rvEuclCahkMWdrd8nMEqe0xmJ9gd47CWwvwLCLZl3EjlVc
          WyDMPvWRaAEp+feNHcWgqq8U6jJvls4hLHqUQr3A5DUp68zBVG0yn9n5HlydvH6tXVdFd
          zrgTIll2y2vJJfdEY9eGd6YclJBMmVTCNvgCVs1ovYA1IZAehWjH3QgGRzKiyQ=
        - Upc3AwZF8KqgKt2Tma4NQ1f73sCYKvYTD48a07y3ngtwr0CLUwMLOap8LxTiA8qnzXYKt
          qVQirbTHsOKF+o85Hk4L9TpAgodvw2rDAK7Q7IAnd4ymufpE+WTtHHJQ+0Dp2gIp2DOj+
          BUAR64RG/fald0T6wIwhiM4ASUVzJXpmmQm+c5g2tYFvucN6TJ+xlvUpKwtfmp2fDME1v
          gDQkyhD77M8dM3Lj67MRzfEHIArNQQTKDzLVCoqVyDD2K9vg/l667YctpVg2cLXIV7Z3G
          Fz/cYnVr53J4Zce/JK6h9f3RewxbYCmXmT6XlPccY8SRS7e8SteJFR4YnlglFcyPlrE7n
          yeI0sKBTzsOyB15r5j+j327hkUnBOHIL2PpHrjlW+vZ+HdOsUYG83uIa3hudPaCCwv9sq
          GrvybeH+W7CqTmtwpdlV0lnkiRfcKyW7WY8IjrSXIlQHslSs7BeFNAyHir5lLQoVP36R4
          hE4GJhxd9heBZpah1qF8xaZ5PyqZZ3o3qdlD3G49OWLDTFGuL/CcdYburHdR/vTwOa9B3
          zT/oCELrxmptBoxTWzD/JWDVjDm26D/gImJgDNAXX1qSKSfIqy6D87TY/oBZza2RXiTV+
          30ayvaTcYue+vPHL5WXSHqWq/27haqzfdStKQspPi+SPDpBipCz+cZzDse1WXI=
        - hHMmK1Ih7MZ5Kp9pqYN+rhGbH+RE2yEJFupfrDxduqX7Mca2g5fGFHzEhB8YAUByLagCE
          elad0EuKAYrkI98e5fjjGr9XPIP0+V8+k6gY0eSZsQYRDKnin2HiLppKiRXpV9efIfStT
          kYxX7eJB74fLZ1pfw6pP7PgijjqbO+QdrvD/Bvr9KERgiY2suUD/NLJHQdAeVINLIH7gm
          t/SUIuCpBC7job26OohsSTzH3Am2hK6MktvWhTwxUdicxsNUisVL/G/jUFo6DVXIFXCGT
          SUsPbBTnHfWh+xAfdGrkoXHomUJhESwCDewizx8SHzvR99bbh1YfEc8pI05aNFGU/t160
          zsD9dcDQXxF6Wa0okBOqXcFtkJa8lozffzGbGt+LBuOyznM5gmQuUvuJUSi2L8fwjTaZG
          X+BfTm9FPr5ok43Rio+z5Zb0Wv/V8y8oIho21y9qRPWC4DkxJ43N96wVUPBhlD+cjDoqD
          YNvsDE4UuYusF/9G2hPp0ZQptxRWm/fz6BPd+1nXN8DX2ZasGsjz3nTyzuh6OKv9ZCrMF
          tXNEVmFCUsAUuYZlWCNxqsDeF0xuTfDyhtrcQj0T6cMIydyHiuNyJkJf4RzMT9+iNMAjR
          mmCan1JBYfBzN4Kzwq+TbHEgSAmDCpO0HwYQ7ZJn9oQIOvPYt/RQ4aTxc4xGB8=
