# permissions for end users to view ipsecpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipsec-policy-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipsecpolicy-viewer-role
rules:
- apiGroups:
  - starlingx.io
  resources:
  - ipsecpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlingx.io
  resources:
  - ipsecpolicies/status
  verbs:
  - get
