---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipsec-policy-agent-operator
    control-plane: controller-manager
  name: ipsec-policy-agent-controller-manager-metrics-service
  namespace: ipsec-policy-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager