---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipsec-policy-agent-operator
  name: ipsec-policy-agent-controller-manager
  namespace: ipsec-policy-operator