resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: starlingx/stx-ipsec-policy-manager-operator
  newTag: master-debian-stable-latest
