- hosts: all
  tasks:
    - name: Find coverage report directory
      stat:
        path: "{{ zuul.project.src_dir }}/python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/UTCoverage"
      register: coverage_dir

    - name: Upload coverage reports
      synchronize:
        src: "{{ zuul.project.src_dir }}/python3-k8sapp-ipsec-policy-operator/k8sapp_ipsec_policy_operator/UTCoverage/"
        dest: "{{ zuul.executor.log_root }}/coverage/"
        mode: pull
      when: coverage_dir.stat.exists
      failed_when: false

    - name: Return coverage report artifact
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Coverage Report"
                url: "coverage/coverage_report.txt"
      when: coverage_dir.stat.exists
      failed_when: false
