---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 666
      targetPort: 6666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: centos-tools
          image: docker.io/centos/tools:latest
          command: ["/bin/sh", "-c", "python2 /script/server.py 6666"]
          ports:
            - containerPort: 6666
          volumeMounts:
            - name: script-volume
              mountPath: /script
      nodeSelector:
        kubernetes.io/hostname: controller-1
      volumes:
        - name: script-volume
          configMap:
            name: server-script
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: client-ds
  labels:
    app: centos-tools
spec:
  selector:
    matchLabels:
      app: centos-tools
  template:
    metadata:
      labels:
        app: centos-tools
    spec:
      containers:
      - name: centos-tools-container
        image: docker.io/centos/tools:latest
        command: ["/bin/sh", "-c", "sleep inf"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-script
data:
  server.py: |
    import socket
    import argparse
    from BaseHTTPServer import HTTPServer
    from SimpleHTTPServer import SimpleHTTPRequestHandler

    class MyHandler(SimpleHTTPRequestHandler):
        def do_GET(self):
            if self.path == '/ip':
                self.send_response(200)
                self.send_header('Content-type', 'text/html')
                self.end_headers()
                self.wfile.write('Your IP address is %s' % self.client_address[0])
            else:
                return SimpleHTTPRequestHandler.do_GET(self)

    class HTTPServerV6(HTTPServer):
        address_family = socket.AF_INET6

    def main():
        parser = argparse.ArgumentParser(
            description='Start an HTTP server with IPv6 support.')
        parser.add_argument('port', type=int, help='Port number to listen on')
        args = parser.parse_args()

        server = HTTPServerV6(('::', args.port), MyHandler)
        print("Starting server on port %d..." % args.port)
        server.serve_forever()

    if __name__ == '__main__':
        main()

